language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=4.4.7
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: npm install
script:
  - mvn clean
  #- mvn test
  - gulp test
  - mvn package -Pprod -DskipTests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/17ee4a906ab3be024e7d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
